#!/bin/bash
# Can supply additional arguments, e.g. ./start_server --debug
voila Covid-TTQ4.ipynb \
    --no-browser \
    --show_tracebacks=True \
    --MappingKernelManager.cull_interval=120 \
    --MappingKernelManager.cull_idle_timeout=600 \
    "$@"